-- 社内備品の貸出管理システム: 初期スキーマ
--
-- PostgreSQL と H2（PostgreSQL 互換モード）の両方で動く SQL だけを使っている。
-- （例: GENERATED BY DEFAULT AS IDENTITY はどちらもサポートする）

CREATE TABLE department (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    CONSTRAINT uq_department_code UNIQUE (code)
);

CREATE TABLE employee (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(20)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    department_id   BIGINT       NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_employee_number UNIQUE (employee_number),
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE TABLE asset_category (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(50) NOT NULL,
    default_loan_days  INTEGER     NOT NULL,
    CONSTRAINT uq_asset_category_name UNIQUE (name)
);

CREATE TABLE asset (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_number VARCHAR(30)  NOT NULL,
    name              VARCHAR(150) NOT NULL,
    category_id       BIGINT       NOT NULL,
    manufacturer      VARCHAR(100),
    model             VARCHAR(100),
    status            VARCHAR(20)  NOT NULL,
    purchased_on      DATE,
    note              VARCHAR(500),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_asset_management_number UNIQUE (management_number),
    CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES asset_category (id)
);

CREATE TABLE loan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id      BIGINT      NOT NULL,
    requester_id  BIGINT      NOT NULL,
    approver_id   BIGINT,
    status        VARCHAR(20) NOT NULL,
    requested_at  TIMESTAMP   NOT NULL,
    started_on    DATE,
    due_on        DATE,
    returned_on   DATE,
    reject_reason VARCHAR(300),
    return_note   VARCHAR(300),
    version       BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_loan_asset FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_loan_requester FOREIGN KEY (requester_id) REFERENCES employee (id),
    CONSTRAINT fk_loan_approver FOREIGN KEY (approver_id) REFERENCES employee (id)
);

CREATE TABLE loan_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id    BIGINT      NOT NULL,
    actor_id   BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,
    action     VARCHAR(50) NOT NULL,
    note       VARCHAR(300),
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT fk_loan_history_loan FOREIGN KEY (loan_id) REFERENCES loan (id),
    CONSTRAINT fk_loan_history_actor FOREIGN KEY (actor_id) REFERENCES employee (id)
);

-- 一覧系 API の検索条件に対応するためのインデックス
CREATE INDEX idx_asset_status ON asset (status);
CREATE INDEX idx_asset_category ON asset (category_id);
CREATE INDEX idx_loan_requester_status ON loan (requester_id, status);
CREATE INDEX idx_loan_asset_status ON loan (asset_id, status);
CREATE INDEX idx_loan_status_due ON loan (status, due_on);
CREATE INDEX idx_loan_history_loan ON loan_history (loan_id, created_at);
